### ISSUE TITLE
getSrc is fragile with nara

### ISSUE THREAD

**Issue by dogrdon** [dogrdon/accidentalculture#2]
It is stuff like this that is killing me:

`TRYING TO GET srcUrl for http://research.archives.gov/description/89689
/Users/quomo/accidentalculture/lib/accidentalculture/download.rb:122:in`getSrc': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/quomo/accidentalculture/lib/accidentalculture/download.rb:129:in`download_videos'
    from accidentalculture.rb:36:in `block in get_results'
    from accidentalculture.rb:36:in`each'
    from accidentalculture.rb:36:in `get_results'
    from accidentalculture.rb:38:in`get_results'
    from accidentalculture.rb:33:in `get_results'
    from accidentalculture.rb:33:in`get_results'
    from accidentalculture.rb:33:in `get_results'
    from accidentalculture.rb:33:in`get_results'
    from accidentalculture.rb:44:in `<main>'`

**Comment by dogrdon** [comment]
just raising error and dipping if raised.
